version: '3'

services:
  site1:
    image: nginx
    volumes:
      - ./site1/www:/var/www/html
      - ./site1/conf.d:/etc/nginx/conf.d
    networks:
      - sites

  site2:
    image: nginx
    volumes:
      - ./site2/www:/var/www/html
      - ./site2/conf.d:/etc/nginx/conf.d
    networks:
      - sites

  balancer:
    image: nginx
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sites
    ports:
      - 80:80
    depends_on:
      - site1
      - site2

networks:
  sites: